### ISSUE TITLE
Task and Questions

### ISSUE THREAD

**Issue by Jojobeere** [HTW-Runner/HoagieShop#1]
https://people.f4.htw-berlin.de/~weberwu/info3/Labs/Lab8-Rails-Dash.shtml
- [x] How to generate a test database/test data for databases with rake?
- [x] Insert, add delete data in the database
- [x] Purchase Hoagie (Order Application)
- [x] Reviews and Selfies (Admin Review Selfie)
- [x] Statistics
- [x] Pretty website UI/UX

**Comment by hummingly** [comment]
We're done :)!

**Comment by hummingly** [comment]
We're done :)!
